import Head from "next/head";
import { ReactNode } from "react";
import Navbar from "./Navbar";

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-screen w-screen flex-col bg-white">
        <Navbar />
        <main className="flex flex-col h-full bg-white overflow-y-auto">
          {children}
        </main>
      </div>
    </>
  );
}
