import Head from 'next/head'
import LandingLayout from '@/components/LandingLayout'

export default function Feed() {
  return (
    <>
      <Head>
        <title>Feed | Catherd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingLayout title="Feed" description="Latest events">
        <div>This is the feed page</div>
      </LandingLayout>
    </>
  )
}
